ext_dir_map = {
    # No name
    ("noname",): ("Other", "Uncategorized"),
    # Audio
    (
        ".aac",
        ".aif",
        ".cda",
        ".flac",
        ".m3u",
        ".m4a",
        ".mid",
        ".midi",
        ".mp3",
        ".mpa",
        ".ogg",
        ".opus",
        ".wav",
        ".wma",
        ".wpl",
    ): ("Media", "Audio"),
    # Books
    (".epub",): ("Books",),
    # Compressed files
    (".7z", ".arj", ".deb", ".pkg", ".rar", ".rpm", ".tar.gz", ".z", ".zip"): (
        "Compressed",
    ),
    # Data
    (
        ".csv",
        ".dat",
        ".db",
        ".dbf",
        ".json",
        ".log",
        ".mdb",
        ".pdb",
        ".sav",
        ".sql",
        ".sqlite",
        ".sqlite3",
        ".tar",
        ".xml",
    ): ("Programming", "Database"),
    # Disc
    (".bin", ".dmg", ".iso", ".toast", ".vcd"): ("Other", "Disc"),
    # Documents
    (".doc", ".docx"): ("Text", "Word"),
    (".pdf",): ("Text", "PDF"),
    (".sla",): ("Text", "Resume"),
    (".txt", ".rtf", ".tex", ".wks", ".wps", ".wpd", ".odt", ".wiki"): (
        "Text",
        "TextFiles",
    ),
    # Executables
    (
        ".apk",
        ".bat",
        ".bin",
        ".cgi",
        ".com",
        ".exe",
        ".gadget",
        ".jar",
        ".pl",
        ".wsf",
    ): ("Executables",),
    # Fonts
    (".fnt", ".fon", ".eot", ".otf", ".ttf", ".woff", ".woff2"): ("Fonts"),
    # Images
    (
        ".CR2",
        ".ai",
        ".bmp",
        ".eps",
        ".gif",
        ".ico",
        ".jpeg",
        ".jpg",
        ".png",
        ".ps",
        ".psd",
        ".svg",
        ".tif",
        ".tiff",
        ".webp",
        ".xcf",
        ".xps",
    ): ("Media", "Images"),
    # Internet
    (
        ".asp",
        ".aspx",
        ".cer",
        ".cfm",
        ".cgi",
        ".pl",
        ".css",
        ".htm",
        ".html",
        ".js",
        ".jsp",
        ".part",
        ".php",
        ".rss",
        ".xhtml",
    ): ("Other", "Internet"),
    # Mathematics
    (".tex", ".ggb"): ("Mathematics",),
    # Presentations
    (".key", ".odp", ".pps", ".ppt", ".pptx"): ("Text", "Presentations"),
    # Programming
    (
        ".c",
        ".class",
        ".cpp",
        ".cs",
        ".dart",
        ".h",
        ".html",
        ".ipynb",
        ".java",
        ".py",
        ".rb",
        ".sh",
        ".swift",
        ".vb",
    ): ("Programming", "SourceCode"),
    # Security
    (".cer", ".gpg", "kdb", "kdbx", ".asc", ".kbx", ".key", ".pub"): (
        "Security",
    ),
    # Spreadsheets
    (".ods", ".xlr", ".xls", ".xlsx"): ("Text", "Spreadsheets"),
    # System
    (
        ".bak",
        ".cab",
        ".cfg",
        ".cpl",
        ".cur",
        ".dll",
        ".dmp",
        ".drv",
        ".icns",
        ".ico",
        ".ini",
        ".lnk",
        ".msi",
        ".sys",
        ".tmp",
    ): ("Text", "Other", "System"),
    # Torrent
    (".torrent"): ("Torrents",),
    # Video
    (
        ".3g2",
        ".3gp",
        ".avi",
        ".flv",
        ".h264",
        ".m4v",
        ".mkv",
        ".mov",
        ".mp4",
        ".mpeg",
        ".mpg",
        ".rm",
        ".swf",
        ".vob",
        ".webm",
        ".wmv",
    ): ("Media", "Video"),
}
